# Generated by Django 5.0.6 on 2024-06-26 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_created',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile', to='chat.userprofile'),
        ),
    ]
